# https://docs.docker.com/compose/environment-variables/#the-env-file
services:
  um_srvc:
    image: ${IMG_ID}
    network_mode: host
    privileged: false
    volumes:
      - /dev:/dev # to access ttyUSB devices
      # This line allows running graphical applications in the container and visualizing them on the host.
      # This works provided that the host has a display connected (so the X11 socket exists) and the
      # necessary permissions have been granted (e.g. by running `xhost +local:` on the host).
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./um${UM_MODEL}_params.yaml:/tmp/params.yaml # Parameters
      - ./exec_launch_file.sh:/tmp/exec_launch_file.sh
    device_cgroup_rules:
      - "c 188:* rwm" # 188 is ttyUSB devices
    environment:
      NAMESPACE: ${NAMESPACE:-} # Optional
      ROBOT_NAME: ${ROBOT_NAME:-robot} # Required
      UM_MODEL: ${UM_MODEL} # Required: 6 or 7
      PARAMS_FILE: /tmp/params.yaml # Required
      # TOPIC_REMAPPINGS is optional.
      TOPIC_REMAPPINGS: "imu/data:=um${UM_MODEL}/data,imu/mag:=um${UM_MODEL}/mag,imu/rpy:=um${UM_MODEL}/rpy,imu/temperature:=um${UM_MODEL}/temperature,imu/reset:=um${UM_MODEL}/reset"
      # NODE_OPTIONS is optional.
      # Attention should be paid to the node's name given here, 'umx_ros2_driver'.
      # If name is not provided the default value used for the node's name is 'umx_ros2_driver'.
      NODE_OPTIONS: "name=umx_ros2_driver,output=screen,emulate_tty=True,respawn=False,respawn_delay=0.0"
      # LOGGING_OPTIONS is optional.
      # Attention should be paid to the loggers:
      #  <NAMESPACE>.<ROBOT_NAME>.<NODE_OPTIONS.name>=debug.
      #  um${UM_MODEL}_driver=debug.
      LOGGING_OPTIONS: "log-level=info,disable-stdout-logs=true,disable-rosout-logs=false,disable-external-lib-logs=true,test.robot.umx_ros2_driver=debug,um${UM_MODEL}_driver=debug"
      RCUTILS_LOGGING_BUFFERED_STREAM: "0"
      RCUTILS_LOGGING_USE_STDOUT: "1"
      RCUTILS_COLORIZED_OUTPUT: "1"
      RCUTILS_CONSOLE_OUTPUT_FORMAT: "[{severity} {time}] [{name}]: {message} ({file_name}:L{line_number})"
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-11}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_zenoh_cpp}
