# https://docs.docker.com/compose/environment-variables/#the-env-file
services:
  umx_srvc:
    image: ${IMG_ID}
    network_mode: host
    privileged: false
    ipc: host
    volumes:
      - /dev:/dev # to access serial devices (e.g., /dev/ttyUSB*)
      # Why map /run/udev from host into the container?
      # - udev runs on the HOST and stores a volatile database of device properties/states under /run/udev.
      # - Mounting it read-only lets tools and libraries inside the container read udev attributes (IDs, symlinks,
      #   tags) so their view matches the host.
      # - It improves detection/consistency when dealing with hotplug. Note: udev events do NOT propagate into
      #   the container; this mount is only for reading metadata/state.
      - /run/udev:/run/udev:ro
      - /etc/udev/rules.d:/etc/udev/rules.d:ro
      # Uncomment the params file you want to use for UMX.
      - ./um7_params.yaml:/tmp/params.yaml:ro
      # - ./um6_params.yaml:/tmp/params.yaml:ro
      - ./cyclonedds_config.xml:/tmp/cyclonedds_config.xml:ro
    devices:
      - /dev/dri:/dev/dri
    device_cgroup_rules:
      - "c 188:* rwm" # 188 is ttyUSB devices
    # Environment variables passed to the container.
    # Keep PARAMS_FILE explicit here because it must match the path defined in 'volumes' above.
    environment:
      TERM: xterm-256color
      RCUTILS_LOGGING_BUFFERED_STREAM: "0"
      RCUTILS_LOGGING_USE_STDOUT: "1"
      RCUTILS_COLORIZED_OUTPUT: "1"
      RCUTILS_CONSOLE_OUTPUT_FORMAT: "[{severity} {time}] [{name}]: {message} ({file_name}:L{line_number})"
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: file:///tmp/cyclonedds_config.xml
      ROS_DOMAIN_ID: "11"
      NAMESPACE: "test"
      ROBOT_NAME: "robot"
      UM_MODEL: "7"
      PARAMS_FILE: /tmp/params.yaml
      TOPIC_REMAPPINGS: "imu/data:=um7/data,imu/mag:=um7/mag,imu/rpy:=um7/rpy,imu/temperature:=um7/temperature,imu/reset:=um7/reset"
      NODE_OPTIONS: "name=umx_ros2_handler,output=screen,emulate_tty=True,respawn=False,respawn_delay=0.0"
      LOGGING_OPTIONS: "log-level=info,disable-stdout-logs=true,disable-rosout-logs=false,disable-external-lib-logs=true"
      # When using UM6 params, set:
      # UM_MODEL: \"6\"
      # TOPIC_REMAPPINGS: \"imu/data:=um6/data,imu/mag:=um6/mag,imu/rpy:=um6/rpy,imu/temperature:=um6/temperature,imu/reset:=um6/reset\"
      # For ROS2-Humble, and earlier versions of ROS2, to limit the discovery to localhost only.
      # ROS_LOCALHOST_ONLY: 1|0
      # Since ROS2-Jazzy, more options are available to configure the DDS discovery behaviour:
      # ROS_AUTOMATIC_DISCOVERY_RANGE: LOCALHOST|SUBNET|OFF|SYSTEM_DEFAULT
      # ROS_STATIC_PEERS='192.168.0.1;remote.com'
