# Attention should be paid to the node's name.
/**/umx_ros2_driver:
  ros__parameters:
    port: /dev/ttyUSB0
    baud: 115200
    update_rate: 20
    mag_updates: true
    quat_mode: True
    zero_gyros: True
    frame_id: $(var robot_prefix)imu_link
    linear_acceleration_stdev: 0.0392266
    angular_velocity_stdev: 0.0010471966666666666
    orientation_x_stdev: 0.052359878
    orientation_y_stdev: 0.052359878
    orientation_z_stdev: 0.087266463
    tf_ned_to_enu: True
    orientation_in_robot_frame: False
