/**/livox_gen2_lidar_ros2_driver:
  ros__parameters:
    user_config_path: "{{user_config_path}}"
    frame_id: "{{robot_prefix}}livox_frame"
    xfer_format: 0
    multi_topic: 1
    data_src: 0
    publish_freq: 10.0
    output_data_type: 0
    lvx_file_path: "/tmp/livox_test.lvx"
    cmdline_input_bd_code: "livox0000000001"
