# https://docs.docker.com/compose/environment-variables/#the-env-file
services:
  robosense_srvc:
    image: ${IMG_ID}
    network_mode: host
    privileged: false
    ipc: host
    volumes:
      # Uncomment the config file you want to use for RoboSense.
      - ./example_1.front_robosense_helios_16p_config.yaml:/tmp/config.yaml:ro
      # - ./example_2.front_back_robosense_helios_16p_config.yaml:/tmp/config.yaml:ro
      - ./cyclonedds_config.xml:/tmp/cyclonedds_config.xml:ro
    devices:
      - /dev/dri:/dev/dri
    # Environment variables passed to the container.
    # Keep CONFIG_FILE explicit here because it must match the path defined in 'volumes' above.
    # This improves visibility and avoids hiding this fixed mapping inside the external .env file.
    environment:
      TERM: xterm-256color
      RCUTILS_LOGGING_BUFFERED_STREAM: "0"
      RCUTILS_LOGGING_USE_STDOUT: "1"
      RCUTILS_COLORIZED_OUTPUT: "1"
      RCUTILS_CONSOLE_OUTPUT_FORMAT: "[{severity} {time}] [{name}]: {message} ({file_name}:L{line_number})"
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: file:///tmp/cyclonedds_config.xml
      ROS_DOMAIN_ID: "11"
      NAMESPACE: "test"
      ROBOT_NAME: "robot"
      CONFIG_FILE: /tmp/config.yaml
      # TOPIC_REMAPPINGS is not supported in RoboSense (set topics in config file)
      NODE_OPTIONS: "name=robosense_lidar_ros2_handler,output=screen,emulate_tty=True,respawn=False,respawn_delay=0.0"
      LOGGING_OPTIONS: "log-level=info,disable-stdout-logs=true,disable-rosout-logs=false,disable-external-lib-logs=true"
      # For ROS2-Humble, and earlier versions of ROS2, to limit the discovery to localhost only.
      # ROS_LOCALHOST_ONLY: 1|0'
      # Since ROS2-Jazzy, more options are available to configure the DDS discovery behaviour:
      # ROS_AUTOMATIC_DISCOVERY_RANGE: LOCALHOST|SUBNET|OFF|SYSTEM_DEFAULT
      # ROS_STATIC_PEERS='192.168.0.1;remote.com'
