services:
  livox_gen2_lidar_srvc:
    image: ${IMG_ID}
    network_mode: host
    privileged: false
    volumes:
      # This line allows running graphical applications in the container and visualizing them on the host.
      # This works provided that the host has a display connected (so the X11 socket exists) and the
      # necessary permissions have been granted (e.g. by running `xhost +local:` on the host).
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./${JSON_FILE}:/tmp/config.json
      - ./${YAML_FILE}:/tmp/params.yaml
      - ./exec_launch_file.sh:/tmp/exec_launch_file.sh
      - ../eut_sensor.launch.py:/home/sensor/workspace/src/livox_ros_driver2/launch_ROS2/eut_sensor.launch.py
    environment:
      NAMESPACE: ${NAMESPACE:-} # Optional
      ROBOT_NAME: ${ROBOT_NAME:-robot} # Required
      CONFIG_FILE: /tmp/config.json # Required
      PARAMS_FILE: /tmp/params.yaml # Required
      # TOPIC_REMAPPINGS is optional.
      TOPIC_REMAPPINGS: "livox/lidar_192_168_1_193:=front_lidar/scan/points,livox/imu_192_168_1_193:=front_lidar/imu/data"
      # NODE_OPTIONS is optional.
      # Attention should be paid to the node's name given here, 'livox_gen2_lidar_ros2_driver'.
      # If name is not provided the default value used for the node's name is 'livox_gen2_lidar_ros2_driver'.
      NODE_OPTIONS: "name=livox_gen2_lidar_ros2_driver,output=screen,emulate_tty=True,respawn=False,respawn_delay=0.0"
      # LOGGING_OPTIONS is optional.
      # Attention should be paid to the loggers:
      #  <NAMESPACE>.<ROBOT_NAME>.<NODE_OPTIONS.name>=debug.
      LOGGING_OPTIONS: "log-level=info,disable-stdout-logs=false,disable-rosout-logs=false,disable-external-lib-logs=true"
      RCUTILS_LOGGING_BUFFERED_STREAM: "0"
      RCUTILS_LOGGING_USE_STDOUT: "1"
      RCUTILS_COLORIZED_OUTPUT: "1"
      RCUTILS_CONSOLE_OUTPUT_FORMAT: "[{severity} {time}] [{name}]: {message} ({file_name}:L{line_number})"
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-11}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_zenoh_cpp}
