# https://docs.docker.com/compose/environment-variables/#the-env-file
services:
  livox_gen2_srvc:
    image: ${IMG_ID}
    network_mode: host
    privileged: false
    ipc: host
    volumes:
      # Uncomment the JSON config file you want to use for Livox Gen2.
      - ./example_1.front_livox_mid360.json:/tmp/user_config.json:ro
      # - ./example_2.front_back_livox_mid360.json:/tmp/user_config.json:ro
      # Uncomment the params file you want to use for Livox Gen2.
      - ./example_1.front_livox_mid360.yaml:/tmp/params.yaml:ro
      # - ./example_2.front_back_livox_mid360.yaml:/tmp/params.yaml:ro
      - ./cyclonedds_config.xml:/tmp/cyclonedds_config.xml:ro
    devices:
      - /dev/dri:/dev/dri
    # Environment variables passed to the container.
    # Keep PARAMS_FILE explicit here because it must match the path defined in 'volumes' above.
    environment:
      TERM: xterm-256color
      RCUTILS_LOGGING_BUFFERED_STREAM: "0"
      RCUTILS_LOGGING_USE_STDOUT: "1"
      RCUTILS_COLORIZED_OUTPUT: "1"
      RCUTILS_CONSOLE_OUTPUT_FORMAT: "[{severity} {time}] [{name}]: {message} ({file_name}:L{line_number})"
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: file:///tmp/cyclonedds_config.xml
      ROS_DOMAIN_ID: "11"
      NAMESPACE: "test"
      ROBOT_NAME: "robot"
      PARAMS_FILE: /tmp/params.yaml
      TOPIC_REMAPPINGS: ""
      NODE_OPTIONS: "name=livox_gen2_lidar_ros2_handler,output=screen,emulate_tty=True,respawn=False,respawn_delay=0.0"
      LOGGING_OPTIONS: "log-level=info,disable-stdout-logs=true,disable-rosout-logs=false,disable-external-lib-logs=true"
      # For ROS2-Humble, and earlier versions of ROS2, to limit the discovery to localhost only.
      # ROS_LOCALHOST_ONLY: 1|0
      # Since ROS2-Jazzy, more options are available to configure the DDS discovery behaviour:
      # ROS_AUTOMATIC_DISCOVERY_RANGE: LOCALHOST|SUBNET|OFF|SYSTEM_DEFAULT
      # ROS_STATIC_PEERS='192.168.0.1;remote.com'
